openapi: 3.0.0

info:
  title: Bored API
  version: 1.0.0
  description: API to retrieve random activities when bored

servers:
  - url: http://www.boredapi.com/api

paths:
  /activity:
    get:
      summary: Get a specific activity
      description: Retrieve an activity with specified parameters
      parameters:
        - name: key
          in: query
          description: Unique key of the activity
          required: false
          schema:
            type: string
        - name: type
          in: query
          description: Type of activity
          required: false
          schema:
            type: string
        - name: participants
          in: query
          description: Number of participants
          required: false
          schema:
            type: integer
        - name: price
          in: query
          description: Price level of the activity
          required: false
          schema:
            type: number
        - name: accessibility
          in: query
          description: Accessibility level of the activity
          required: false
          schema:
            type: number
        - name: minprice
          in: query
          description: Minimum price level of the activity
          required: false
          schema:
            type: number
        - name: maxprice
          in: query
          description: Maximum price level of the activity
          required: false
          schema:
            type: number
        - name: minaccessibility
          in: query
          description: Minimum accessibility level of the activity
          required: false
          schema:
            type: number
        - name: maxaccessibility
          in: query
          description: Maximum accessibility level of the activity
          required: false
          schema:
            type: number
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  activity:
                    type: string
                  type:
                    type: string
                  participants:
                    type: integer
                  price:
                    type: number
                  accessibility:
                    type: number
                  key:
                    type: string
                  link:
                    type: string
              example:
                activity: "Learn how to play a new sport"
                type: "recreational"
                participants: 1
                price: 0.1
                accessibility: 0.2
                key: "5808228"
                link: "https://www.wikihow.com/Play-Basketball"
        default:
          description: No activity found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "No activity found with the specified parameters"
